### ISSUE TITLE
Please include flac.opam in release tarball

### ISSUE THREAD

**Issue by paddatrapper** [savonet/ocaml-flac#10]
Trying to build from the release tarball for 2.0.0 results in the following error:

```
./bootstrap
cat: flac.opam: No such file or directory
```
For the debian packaging of 0.2.0, I have worked around it by patching the file back from the Github repo.

**Comment by toots** [comment]
Thanks for the report! It is fixed now.

BTW, I would recommend to monitor the versions conflicts for liquidsoap. I believe that these packages are mostly used by us and there are a couple of recent releases that are meant for the on-going development branch so we should probably avoid pushing them to debian for now.

Until liquidsoap `2.0` is out, I'm committed to fixing any issues in the binding's version that are used by the latest released liquidsoap to make sure to hit us up if that happen!

**Comment by paddatrapper** [comment]
Thanks. Sure, will do
